<?php

namespace TMSolution\CronBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CronTaskRepository extends EntityRepository
{

    public function getOneTask()
    {
        return $this->createQueryBuilder('ct')
                        ->where('ct.firstRun <= :currentDate')
                        ->andWhere('ct.disabled = 0')
                        ->andWhere('ct.used = 0')
                        ->setParameter('currentDate', new \DateTime('now'), \Doctrine\DBAL\Types\Type::DATETIME)
                        ->orderBy('ct.firstRun')
                        ->setMaxResults(1)
                        ->getQuery()
                        ->getOneOrNullResult();
    }
    
    public function getNewTasks($maxResult=10)
    {
        return $this->createQueryBuilder('ct')
                        ->where('ct.firstRun <= :currentDate')
                        ->andWhere('ct.disabled = 0')
                        ->andWhere('ct.used = 0')
                        ->setParameter('currentDate', new \DateTime('now'), \Doctrine\DBAL\Types\Type::DATETIME)
                        ->orderBy('ct.firstRun')
                        ->setMaxResults($maxResult)
                        ->getQuery()
                        ->getResult();
    }

}
